"""Writers — emit data.js (for the dashboard), CSV, and an extraction log."""

from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Iterable

from .engine import Transaction

# Reasonable default palette. Categories not listed get the dashboard's default color.
DEFAULT_PALETTE: dict[str, str] = {
    "Mortgage":      "#10b981",
    "Healthcare":    "#f87171",
    "Subscriptions": "#6ea8fe",
    "Investments":   "#facc15",
    "Travel":        "#a78bfa",
    "Auto":          "#fb923c",
    "Utilities":     "#34d399",
    "Insurance":     "#06b6d4",
    "Shopping":      "#f472b6",
    "Personal Care": "#22d3ee",
    "Family":        "#fbbf24",
    "Recreation":    "#4ade80",
    "Education":     "#818cf8",
    "Dining":        "#fde68a",
    "Refunds":       "#9ca3af",
    "Uncategorized": "#6b7280",
}


def _js_string(s: str) -> str:
    return json.dumps(s)


def write_data_js(
    path: Path,
    transactions: Iterable[Transaction],
    *,
    title: str,
    subtitle: str,
    window_label: str,
    currency: str,
    palette: dict[str, str] | None = None,
) -> None:
    palette = palette or DEFAULT_PALETTE
    txs = sorted(transactions, key=lambda t: (t.date, t.merchant))

    lines: list[str] = []
    lines.append("// Auto-generated by extractor/extract.py. Edit senders.json (not this file) to change parsing.")
    lines.append("")
    lines.append("window.DASHBOARD_CONFIG = {")
    lines.append(f"  title: {_js_string(title)},")
    lines.append(f"  subtitle: {_js_string(subtitle)},")
    lines.append(f"  windowLabel: {_js_string(window_label)},")
    lines.append(f"  currency: {_js_string(currency)},")
    lines.append("};")
    lines.append("")
    lines.append("window.CATEGORIES = {")
    for cat, color in palette.items():
        lines.append(f"  {_js_string(cat)}: {_js_string(color)},")
    lines.append("};")
    lines.append("")
    lines.append("window.TRANSACTIONS = [")
    for t in txs:
        fields = [
            f"date: {_js_string(t.date)}",
            f"merchant: {_js_string(t.merchant)}",
            f"category: {_js_string(t.category)}",
            f"amount: {t.amount:.2f}",
        ]
        if t.note:
            fields.append(f"note: {_js_string(t.note)}")
        lines.append("  { " + ", ".join(fields) + " },")
    lines.append("];")
    lines.append("")
    path.write_text("\n".join(lines))


def write_csv(path: Path, transactions: Iterable[Transaction]) -> None:
    txs = list(transactions)
    with path.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["date", "merchant", "category", "amount", "note", "message_id", "sender_rule_id"])
        w.writeheader()
        for t in txs:
            w.writerow(
                {
                    "date": t.date,
                    "merchant": t.merchant,
                    "category": t.category,
                    "amount": f"{t.amount:.2f}",
                    "note": t.note,
                    "message_id": t.message_id,
                    "sender_rule_id": t.sender_rule_id,
                }
            )


def write_extraction_log(path: Path, stats: dict) -> None:
    path.write_text(json.dumps(stats, indent=2, sort_keys=True))
